env_files:
  github_token: ~/Documents/github_token
build:
  binary: swag-yapi
  main: cmd/swag/main.go
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm64
    - 386
archives:
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
